//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaoShare.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaoDBConStr : DbContext
    {
        public HaoDBConStr()
            : base("name=HaoDBConStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tUserDetails> tUserDetails { get; set; }
        public virtual DbSet<tUsers> tUsers { get; set; }
        public virtual DbSet<tLog> tLog { get; set; }
    }
}
