//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaoShare.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLog
    {
        public int ID { get; set; }
        public string fName { get; set; }
        public string fLevel { get; set; }
        public string fMessage { get; set; }
        public Nullable<System.DateTime> fCreateDate { get; set; }
        public string fIP { get; set; }
        public string fCode { get; set; }
    }
}
