//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaoShare.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsers
    {
        public int ID { get; set; }
        public int fStatus { get; set; }
        public bool fIsLock { get; set; }
        public string fWeiXinID { get; set; }
        public string fLoginID { get; set; }
        public string fPassword { get; set; }
        public System.DateTime fCreateDate { get; set; }
        public System.DateTime fUpdateDate { get; set; }
        public string fUpdateIp { get; set; }
        public string fRemark { get; set; }
        public int fIsBind { get; set; }
    }
}
